dependencies {
    api project(':common')
    implementation project(':project-catalog')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'

    runtimeOnly 'com.mysql:mysql-connector-j'

    testImplementation 'com.tngtech.archunit:archunit-junit5:1.3.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.h2database:h2'
}
